/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xCz6G8vh9zX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Toggle } from "@/components/ui/toggle"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function Component() {
  return (
    <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8 mt-24 mb-24">
      <div className="mx-auto grid max-w-[59rem] flex-1 auto-rows-max gap-4">
        <div className="flex items-center gap-4">
          <Button className="h-7 w-7" size="icon" variant="outline">
            <ChevronLeftIcon className="h-4 w-4" />
            <span className="sr-only">Back</span>
          </Button>
          <h1 className="flex-1 shrink-0 whitespace-nowrap text-xl font-semibold tracking-tight sm:grow-0">
            Cozy Mountain
          </h1>
          <Badge className="ml-auto sm:ml-0" variant="outline">
            Draft
          </Badge>
          <div className="hidden items-center gap-2 md:ml-auto md:flex">
            <Button size="sm" variant="outline">
              Discard
            </Button>
            <Button size="sm">Save</Button>
          </div>
        </div>
        <div className="grid gap-4 md:grid-cols-[1fr_250px] lg:grid-cols-3 lg:gap-8">
          <div className="grid auto-rows-max items-start gap-4 lg:col-span-2 lg:gap-8">
            <Card x-chunk="dashboard-07-chunk-0">
              <CardHeader>
                <CardTitle>Details</CardTitle>
                <CardDescription>Lipsum dolor sit amet, consectetur adipiscing elit</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-6">
                  <div className="grid gap-3">
                    <Label htmlFor="name">Name</Label>
                    <Input className="w-full" defaultValue="Cozy Mountain" id="name" type="text" />
                  </div>
                  <div className="grid gap-3">
                    <Label htmlFor="description">Description</Label>
                    <Textarea
                      className="min-h-32"
                      defaultValue="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl nec ultricies ultricies, nunc nisl ultricies nunc, nec ultricies nunc nisl nec nunc."
                      id="description"
                    />
                  </div>
                  <Card>
                    <CardHeader>
                      <CardTitle>Advanced Options</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="grid gap-3">
                        <div className="grid gap-3">
                          <Label htmlFor="duration">Duration</Label>
                          <Input className="w-full" defaultValue="1" id="duration" type="number" />
                        </div>
                        <div className="flex items-center gap-2">
                          <Label htmlFor="allow-additional">Allow Additional People</Label>
                          <Toggle aria-label="Allow Additional People" id="allow-additional" />
                        </div>
                        <div className="grid gap-3">
                          <Label htmlFor="min-people">Minimum People</Label>
                          <Input className="w-full" defaultValue="1" id="min-people" type="number" />
                        </div>
                        <div className="grid gap-3">
                          <Label htmlFor="price-additional">Price Per Additional Person</Label>
                          <Input
                            className="w-full"
                            defaultValue="20"
                            id="price-additional"
                            prefix="$"
                            step="0.01"
                            type="number"
                          />
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </CardContent>
            </Card>
            <Card x-chunk="dashboard-07-chunk-1">
              <CardHeader>
                <CardTitle>Working Hours</CardTitle>
                <CardDescription>Lipsum dolor sit amet, consectetur adipiscing elit</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[100px]">Day</TableHead>
                      <TableHead>Check In</TableHead>
                      <TableHead>Check Out</TableHead>
                      <TableHead>Price</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-semibold">Monday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-monday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-monday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-monday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-monday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-monday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-monday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Tuesday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-tuesday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-tuesday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-tuesday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-tuesday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-tuesday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-tuesday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Wednesday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-wednesday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-wednesday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-wednesday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-wednesday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-wednesday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-wednesday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Thursday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-thursday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-thursday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-thursday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-thursday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-thursday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-thursday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Friday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-friday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-friday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-friday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-friday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-friday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-friday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Saturday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-saturday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-saturday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-saturday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-saturday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-saturday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-saturday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-semibold">Sunday</TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="open-sunday">
                          Check In
                        </Label>
                        <Input defaultValue="09:00" id="open-sunday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="close-sunday">
                          Check Out
                        </Label>
                        <Input defaultValue="17:00" id="close-sunday" type="time" />
                      </TableCell>
                      <TableCell>
                        <Label className="sr-only" htmlFor="price-sunday">
                          Price
                        </Label>
                        <Input defaultValue="100" id="price-sunday" prefix="$" step="0.01" type="number" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell colSpan={4}>
                        <Button className="gap-1 w-full" size="sm" variant="ghost">
                          <CirclePlusIcon className="h-3.5 w-3.5" />
                          Add Working Hours
                        </Button>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </div>
          <div className="grid auto-rows-max items-start gap-4 lg:gap-8">
            <Card x-chunk="dashboard-07-chunk-3">
              <CardHeader>
                <CardTitle>Status</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-6">
                  <div className="grid gap-3">
                    <Label htmlFor="status">Status</Label>
                    <Select>
                      <SelectTrigger aria-label="Select status" id="status">
                        <SelectValue placeholder="Select status" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="draft">Draft</SelectItem>
                        <SelectItem value="published">Active</SelectItem>
                        <SelectItem value="archived">Archived</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="overflow-hidden" x-chunk="dashboard-07-chunk-4">
              <CardHeader>
                <CardTitle>Images</CardTitle>
                <CardDescription>Lipsum dolor sit amet, consectetur adipiscing elit</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-2">
                  <img
                    alt="Image"
                    className="aspect-square w-full rounded-md object-cover"
                    height="300"
                    src="/placeholder.svg"
                    width="300"
                  />
                  <div className="grid grid-cols-3 gap-2">
                    <button>
                      <img
                        alt="Image"
                        className="aspect-square w-full rounded-md object-cover"
                        height="84"
                        src="/placeholder.svg"
                        width="84"
                      />
                    </button>
                    <button>
                      <img
                        alt="Image"
                        className="aspect-square w-full rounded-md object-cover"
                        height="84"
                        src="/placeholder.svg"
                        width="84"
                      />
                    </button>
                    <button className="flex aspect-square w-full items-center justify-center rounded-md border border-dashed">
                      <UploadIcon className="h-4 w-4 text-muted-foreground" />
                      <span className="sr-only">Upload</span>
                    </button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card x-chunk="dashboard-07-chunk-5">
              <CardHeader>
                <CardTitle>Delete</CardTitle>
                <CardDescription>Lipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
              </CardHeader>
              <CardContent>
                <div />
                <Button size="sm" variant="secondary">
                  Delete
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </main>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function CirclePlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 12h8" />
      <path d="M12 8v8" />
    </svg>
  )
}


function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
