import { CreditCard, MapPin, Square, Star, Settings, Zap, Calendar, Landmark, ShoppingCart } from "lucide-react";
import { env } from "./env";

// ****** General app settings ******
export const APP_NAME = "Flik";
export const APP_DESCRIPTION = `Bookings made easy with Flik.`;
export const APP_DOMAIN = env.NEXT_PUBLIC_ROOT_DOMAIN;
export const APP_LANG = "en";
// ****** / General app settings / ******

// ****** Routes ******
/**
 * this will be used both for components like header and footer, and to generate the sitemap
 * WARNING: 
 * have in count that the visibleBy by property only controls the visibility of the route in the header and footer
 * it does not control the access to the route, for that you should use place your route pages in the respective folders
 * (authenticated) or (subscribed) 
 */


export const APP_ROUTES: Route[] = [
  { name: "Features", path: "/", visibleBy: "all" },
  { name: "Pricing", path: "/pricing", visibleBy: "all" },
  { name: "Blog", path: "/blog", visibleBy: "all" },
  { name: "Dashboard", path: `//app.${APP_DOMAIN}/dashboard`, visibleBy: "subscribed" },
];
//this routes will show in the user dropdown of the header (signout is already included by default)
export const USER_ROUTES = [
  { name: "Profile", path: "/profile" },
  { name: "Settings", path: "/settings" },
  { name: "Dashboard", path: "/dashboard" },

];

// ****** / Sidebar Routes / ******
export const SIDEBAR_ROUTES = [
{ name: "Dashboard", icon: Square, path: "/dashboard" },
{ name: "Bookings", icon: Calendar, path: "/bookings" },
{ name: "Transactions", icon: Landmark, path: "/transactions" },
{ name: "Extras", icon: ShoppingCart, path: "/extras" },
{ name: "Spots", icon: MapPin, path: "/spots" },
{ name: "Integrations", icon: Zap, path: "/integrations" },
{ name: "Billing", icon: CreditCard, path: "/billing" },
{ name: "Settings", icon: Settings, path: "/settings" },
];


// ****** Auth settings ******
export const AFTER_SIGNIN_REDIRECT_URL = "/dashboard";
export const AFTER_SIGNUP_REDIRECT_URL = AFTER_SIGNIN_REDIRECT_URL; // where to redirect after the user signs up for the first time, change this if you want to redirect to a different page
export const AFTER_SIGNOUT_REDIRECT_URL = "/";
export const NON_AUTHENTICATED_REDIRECT_URL = "/signin"; // where to redirect if the user is not authenticated and tries to access a page that requires authentication
export const NON_SUBSCRIBED_REDIRECT_URL = "/pricing"; // where to redirect if the user is authenticated but is not subscribed and 
export const AFTER_CUSTOMER_PORTAL_REDIRECT_URL = "/dashboard"; // where to redirect after the user leaves the customer portal

// ****** / Auth settings / ******



// ****** SEO settings ******
export const SEO_TITLE = "Flik"; // recommended 30-65 characters
export const SEO_DESCRIPTION = APP_DESCRIPTION; // recommended 120-320 characters, you can use APP_DESCRIPTION as long as it is within the recommended length range
/*
 * SEO_IMAGE
 * keep this null if you prefer to use the dynamic og:image generated by the app in /api/og/route.tsx,
 * otherwhise set it to the relative path of the image inside the public folder, e.g. "/assets/og-image.png"
 */
export const SEO_IMAGE = null;





// ****** Blog settings ******
// set this to false if you don't want to currently use the blog feature, but you want to keep the code for future use
export const BLOG_ENABLED = false;
// this is the default storage path for blog posts, update this if you move your blog posts to a different folder
export const BLOG_POSTS_PATH = "src/blog_content/posts";
export const BLOG_TITLE = "My blog";
export const BLOG_DESCRIPTION = "This is my blog description";

// ****** / Blog settings / ******




// ****** Store Settings ******

// Redirect for one-time purchases
export const AFTER_PURCHASE_REDIRECT_URL = "/";
// Redirect for subscriptions
export const AFTER_SUBSCRIPTION_REDIRECT_URL = "/dashboard";

export const TRIAL_DAYS = 14
// ****** / Store Settings / ******

export const WOMPI_CENT_MULTIPLIER = 100.000;

// Type definitions


type Route = {
  name: string;
  path: string;
  visibleBy?: "all" | "authenticated" | "subscribed";
};

